## 1. Generate a 3x4 NumPy array with random integers between 1 and 50.

In [ ]:
import random
import numpy as np
a=list([random.randrange(1,50)for i in range(4)]for i in range(3)) # method to generate a random matrix.

arr=np.array(a)


In [ ]:
arr


array([[22, 16,  1, 36],
       [ 7, 22, 25,  9],
       [20,  8, 24,  3]])

#### 1.1 Calculate and print the Mean, Median, and Standard Deviation of the array

In [ ]:
arr.mean(),np.mean(arr)  # method to calculate mean using numpy

(29.25, 29.25)

In [ ]:
np.median(arr) #method to calculate median using numpy

32.5

In [ ]:
np.std(arr)  #method to calculate std deviation using numpy

10.086776271711173

#### 1.2 Print the Sum of all elements and the sum of each row.

In [ ]:
np.sum(arr)  # method to print sum using numpy

193

In [ ]:
for i in range(3):
    print(arr[i].sum())

#ANOTHER METHOD
np.sum(arr,axis=1)  # axis =1 prints sum along each row
# axis=0 will print along the columns.

75
63
55


array([75, 63, 55])

#### 1.3 Reshape the 3x4 array into a 2x6 array and print it.

In [ ]:
arr.reshape(2,6) #method to reshape a matrix using numpy

array([[22, 16,  1, 36,  7, 22],
       [25,  9, 20,  8, 24,  3]])

## 2. Create two (3 * 3) matrices using NumPy and print it. Perform and print the results of the following linear algebra operations.

In [ ]:
import random
import numpy as np
a=list([random.randrange(100)for i in range(3)]for i in range(3))  #creating to 3*3 matrices randomlt
b=list([random.randrange(100)for i in range(3)]for i in range(3))

arr=np.array(a)
arr2=np.array(b)


In [ ]:
# Matrix Addition
np.add(a,b)

array([[ 82, 111,  76],
       [ 82, 138,  62],
       [160,  41, 148]])

In [ ]:
# Matrix Subtraction
np.subtract(a,b)

array([[ 26,  21,  72],
       [-80, -40, -36],
       [ 10,  17, -36]])

In [ ]:
# Matrix multiplication
np.multiply(a,b)


array([[1512, 2970,  148],
       [  81, 4361,  637],
       [6375,  348, 5152]])

In [ ]:
# transpose of a matrix
np.transpose(a)


array([[54,  1, 85],
       [66, 49, 29],
       [74, 13, 56]])

In [ ]:
np.transpose(b)

array([[28, 81, 75],
       [45, 89, 12],
       [ 2, 49, 92]])

In [ ]:
np.linalg.det(a) #method to calculate determinant of a matrix using numpy

-109012.0

In [ ]:
np.invert(a)

array([[-55, -67, -75],
       [ -2, -50, -14],
       [-86, -30, -57]], dtype=int32)